#!/usr/bin/env python3
"""
Collect all content under ``Model_Reproduction/`` into a single
``Model_Reproduction/Model_Reproduction_ALL.txt``.

Sources (recursive, under Model_Reproduction/):
  - all .py, .sh, .txt, .md files (text)
  - all .pdf files (text extracted via PyMuPDF/PyPDF2/pdfplumber)

Skipped:
  - __pycache__/, .git/ directories
  - the output file itself (Model_Reproduction_ALL.txt)
  - binary files (images, weights, etc.) — only the 5 extensions above are collected

Usage:
    python analyse/model_reproduction_to_txt.py
"""

import os
from pathlib import Path

# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPRO_DIR = PROJECT_ROOT / 'Model_Reproduction'
OUTPUT_FILE = REPRO_DIR / 'Model_Reproduction_ALL.txt'

TEXT_EXTS = {'.py', '.sh', '.txt', '.md'}
PDF_EXT = '.pdf'

SKIP_DIRS = {'__pycache__', '.git', '.ipynb_checkpoints'}

# Try PDF readers in preference order
_pdf_readers = []
try:
    import fitz  # PyMuPDF
    _pdf_readers.append(('pymupdf', fitz))
except ImportError:
    pass
try:
    from PyPDF2 import PdfReader
    _pdf_readers.append(('pypdf2', PdfReader))
except ImportError:
    pass
try:
    import pdfplumber
    _pdf_readers.append(('pdfplumber', pdfplumber))
except ImportError:
    pass


def separator(title: str) -> str:
    bar = '=' * 78
    return f'\n\n{bar}\n  {title}\n{bar}\n\n'


def read_text(path: Path) -> str:
    for enc in ('utf-8', 'gbk', 'latin-1', 'cp1252'):
        try:
            return path.read_text(encoding=enc)
        except (UnicodeDecodeError, UnicodeError):
            continue
    raw = path.read_bytes()
    return raw.decode('utf-8', errors='replace')


def _extract_pymupdf(path: Path) -> str:
    doc = fitz.open(str(path))
    pages = []
    for i, page in enumerate(doc):
        text = page.get_text()
        if text and text.strip():
            pages.append(f'--- Page {i + 1} ---\n{text}')
    doc.close()
    return '\n'.join(pages) if pages else '[No extractable text]\n'


def _extract_pypdf2(path: Path) -> str:
    reader = PdfReader(str(path))
    pages = []
    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        if text and text.strip():
            pages.append(f'--- Page {i + 1} ---\n{text}')
    return '\n'.join(pages) if pages else '[No extractable text]\n'


def _extract_pdfplumber(path: Path) -> str:
    pages = []
    with pdfplumber.open(str(path)) as pdf:
        for i, page in enumerate(pdf.pages):
            text = page.extract_text()
            if text and text.strip():
                pages.append(f'--- Page {i + 1} ---\n{text}')
    return '\n'.join(pages) if pages else '[No extractable text]\n'


def read_pdf(path: Path) -> str:
    for name, _ in _pdf_readers:
        try:
            if name == 'pymupdf':
                text = _extract_pymupdf(path)
            elif name == 'pypdf2':
                text = _extract_pypdf2(path)
            else:
                text = _extract_pdfplumber(path)
            if text.strip():
                return text
        except Exception:
            continue
    return '[All PDF readers failed to extract text]\n'


def collect() -> list[str]:
    parts: list[str] = []
    if not REPRO_DIR.is_dir():
        return parts

    for dirpath, dirnames, filenames in os.walk(REPRO_DIR):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fname in sorted(filenames):
            fpath = Path(dirpath) / fname
            if fpath.resolve() == OUTPUT_FILE.resolve():
                continue
            rel = fpath.relative_to(REPRO_DIR)
            ext = fpath.suffix.lower()

            if ext == PDF_EXT:
                parts.append(separator(f'Model_Reproduction  |  {rel}  (PDF)'))
                parts.append(read_pdf(fpath))
            elif ext in TEXT_EXTS:
                parts.append(separator(f'Model_Reproduction  |  {rel}'))
                parts.append(read_text(fpath))

    return parts


def main():
    print(f'Model_Reproduction dir : {REPRO_DIR}')
    print(f'Output file            : {OUTPUT_FILE}')

    parts: list[str] = []
    parts.append(separator('Model_Reproduction — Full Content Snapshot'))
    parts.append(f'Generated by: analyse/model_reproduction_to_txt.py\n')
    parts.append(f'Source root: {REPRO_DIR}\n')
    if _pdf_readers:
        parts.append(f'PDF reader : {", ".join(n for n, _ in _pdf_readers)}\n')
    else:
        parts.append('PDF reader : none available (PDFs will be skipped)\n')
    parts.append('\n')

    parts.extend(collect())

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(''.join(parts), encoding='utf-8')

    size_kb = OUTPUT_FILE.stat().st_size / 1024
    print(f'Done.  {OUTPUT_FILE}  ({size_kb:.1f} KB)')


if __name__ == '__main__':
    main()
