#!/usr/bin/env python3
"""
Collect project documentation/scripts (except models/ and Model_Reproduction/)
into ``docs/LS-Rep_BCD_RSML_3_ALL.txt``.

Sources (recursive):
  - docs/          : all .md, .txt (PDFs excluded — exported separately)
  - train_scripts/ : all .sh, .py
  - analyse/       : all .py (this script itself excluded)
  - Root files     : README.md, .claude/CLAUDE.md, .vscode/sftp.json

Excluded:
  - **models/** — model code is exported separately via models_to_txt.py
  - **Model_Reproduction/** — external repos exported via
    analyse/model_reproduction_to_txt.py → Model_Reproduction/Model_Reproduction_ALL.txt
  - **All PDF files** — docs/参考文献/ PDFs go to docs/参考文献/参考文献_all.txt
    via pdf_references_to_txt.py; other PDFs are not text-project-context
  - **docs/temporary/**, **saved_models/** — skipped via SKIP_DIRS

Usage:
    python analyse/project_to_txt.py
"""

import os
from pathlib import Path


# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = PROJECT_ROOT / 'docs' / 'LS-Rep_BCD_RSML_3_ALL.txt'

COLLECT_DIRS = [
    ('docs',                 PROJECT_ROOT / 'docs'),
    ('train_scripts',        PROJECT_ROOT / 'train_scripts'),
    ('analyse',              PROJECT_ROOT / 'analyse'),
]

FILES_ROOT = [
    'README.md',
    '.claude/CLAUDE.md',
    '.vscode/sftp.json',
]

SKIP_DIRS = {'temporary', '__pycache__', '.git', 'saved_models',
             'summary', 'test_infer', 'logs'}
SKIP_FILES = {'LS-Rep_BCD_RSML_3_ALL.txt', 'Model_Reproduction_ALL.txt',
              '参考文献_all.txt'}

TEXT_EXTS = {'.py', '.md', '.txt', '.sh', '.json', '.yaml', '.yml',
             '.cfg', '.ini', '.toml', '.rst', '.c', '.h', '.cpp', '.hpp'}


def separator(title: str) -> str:
    bar = '=' * 78
    return f'\n\n{bar}\n  {title}\n{bar}\n\n'


def read_text(path: Path) -> str:
    for enc in ('utf-8', 'gbk', 'latin-1', 'cp1252'):
        try:
            return path.read_text(encoding=enc)
        except (UnicodeDecodeError, UnicodeError):
            continue
    raw = path.read_bytes()
    return raw.decode('utf-8', errors='replace')


def collect_directory(root: Path, prefix: str) -> list[str]:
    parts: list[str] = []
    if not root.is_dir():
        return parts

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fname in sorted(filenames):
            if fname in SKIP_FILES:
                continue
            fpath = Path(dirpath) / fname
            rel = fpath.relative_to(PROJECT_ROOT)

            # Skip output file and this script
            if fpath.resolve() == OUTPUT_FILE.resolve():
                continue
            this_script = (PROJECT_ROOT / 'analyse' / 'project_to_txt.py').resolve()
            if fpath.resolve() == this_script:
                continue

            ext = fpath.suffix.lower()

            # Skip ALL PDF files. PDFs under docs/参考文献/ are exported
            # separately via analyse/pdf_references_to_txt.py → docs/参考文献/参考文献_all.txt
            if ext == '.pdf':
                continue

            if ext in TEXT_EXTS:
                parts.append(separator(f'{prefix}  |  {rel}'))
                parts.append(read_text(fpath))

    return parts


def collect_files(file_list: list[str], prefix: str) -> list[str]:
    parts: list[str] = []
    for rel in file_list:
        fpath = PROJECT_ROOT / rel
        if not fpath.is_file():
            parts.append(separator(f'{prefix}  |  {rel}  [MISSING]'))
            continue
        parts.append(separator(f'{prefix}  |  {rel}'))
        parts.append(read_text(fpath))
    return parts


def main():
    print(f'Project root : {PROJECT_ROOT}')
    print(f'Output file  : {OUTPUT_FILE}')

    parts: list[str] = []
    parts.append(separator('LS-Rep_BCD_RSML_3 — Full Project Context (models/ & Model_Reproduction/ excluded)'))
    parts.append(f'Generated by: analyse/project_to_txt.py\n')
    parts.append(f'Project root: {PROJECT_ROOT}\n\n')

    for prefix, path in COLLECT_DIRS:
        print(f'Collecting {prefix}/ ...')
        parts.extend(collect_directory(path, prefix))

    print('Collecting root-level files ...')
    parts.extend(collect_files(FILES_ROOT, 'root'))

    print(f'Writing {OUTPUT_FILE} ...')
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(''.join(parts), encoding='utf-8')

    size_kb = OUTPUT_FILE.stat().st_size / 1024
    print(f'Done.  {OUTPUT_FILE}  ({size_kb:.1f} KB)')


if __name__ == '__main__':
    main()
